
function FaqsSection() {
    return (
        <div className="p-6 animate-fade-up">
            <div className="max-w-4xl mx-auto">
                <h2 className="sm:text-3xl text-2xl font-semibold text-primary mb-12">Frequently Asked Questions</h2>
                <div className="space-y-8">
                    <div className="flex items-start">
                        <div className="flex-shrink-0">
                            <svg className="h-6 w-6 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                            </svg>
                        </div>
                        <div className="ml-4">
                            <h3 className="text-lg font-medium text-slate-900">What should you watch out for ?</h3>
                            <p className="text-[15px] text-slate-600 mt-4 leading-relaxed">The camera and lens information has been generated by artificial intelligence, it’s a good idea to double-check any details that matter to you before buying your gear. <br /><strong>We are not responsible if you purchase equipment that doesn’t meet your needs</strong>.</p>
                        </div>
                    </div>



                    <div className="flex items-start">
                        <div className="flex-shrink-0">
                            <svg className="h-6 w-6 text-primary" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                            </svg>
                        </div>
                        <div className="ml-4">
                            <h3 className="text-lg font-medium text-slate-900">Who is this for ?</h3>
                            <p className="text-[15px] text-slate-600 mt-4 leading-relaxed">Anyone who wants to buy photography gear, new or second-hand.</p>
                        </div>
                    </div>





                </div>
            </div>
        </div>

    )
}

export default FaqsSection